version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./questions.txt:/app/questions.txt
      - jeopardy_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/jeopardy.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      #- NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_URL=https://backjeopardy.oke-phx-tst.splata.penoles.mx
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  jeopardy_data:
    driver: local
