apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jeopardy

resources:
- namespace.yaml
- configmap.yaml
- questions-configmap.yaml
- pvc.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: jeopardy
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: trivia-game

images:
- name: jeopardy-backend
  newTag: latest
- name: jeopardy-frontend
  newTag: latest
