apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jeopardy-data
  namespace: jeopardy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
